Class {
	#name : #DROptimisationExperiment,
	#superclass : #Object,
	#instVars : [
		'movie',
		'timestamp'
	],
	#category : #'Druid-UI'
}

{ #category : #accessing }
DROptimisationExperiment >> movie [

	^ movie
]

{ #category : #accessing }
DROptimisationExperiment >> movie: anObject [

	movie := anObject
]

{ #category : #accessing }
DROptimisationExperiment >> timestamp [

	^ timestamp
]

{ #category : #accessing }
DROptimisationExperiment >> timestamp: anObject [

	timestamp := anObject
]
